### ISSUE TITLE
What's the future of this client and how does it compare to pykube?

### ISSUE THREAD

**Issue by hjacobs** [kubernetes-incubator/client-python#102]
I'm currently using this client for my [Kubernetes Operational View](https://github.com/hjacobs/kube-ops-view) dashboard, but I will probably switch to [pykube](https://github.com/kelproject/pykube) as it looks much cleaner (e.g. config loading does not modify a global object), directly uses `requests` (which I'm using too) and supports `insecure-skip-tls-verify` (see #99).

Did you consider merging this client with `pykube` or what are compelling arguments to use `client-python` instead of `pykube`?

**Comment by mbohlool** [comment]
Most part of this client is auto-generated. That distinguish it from pykube. Generating it make it easier for us to keep it in sync with API changes in main repo. 
Having said that, I have no problem supporting features of pykube here if I get time or get somebody contributes. 
About your specific concerns, our config loader has a version to load configs in a local config object instead of global one (and there is an example for that in examples folder). I plan to support `insecure-skip-tls-verify` when I got time. I considered using `requests` instead of what we have right now (`urllib3`) but didn't see compelling reasons yet to spend time on it.

**Comment by hjacobs** [comment]
@mbohlool thanks for the quick answer :smile:

**Comment by mbohlool** [comment]
Sure.
