### ISSUE TITLE
The cap on websocket-client is preventing consumption of security fixes

### ISSUE THREAD

**Issue by prometheanfire** [kubernetes-incubator/client-python#413]
Please see https://github.com/websocket-client/websocket-client/compare/v0.40.0...master for what you're missing.

Can it be removed?  master is currently at `websocket-client>=0.32.0,<=0.40.0 # LGPLv2+`

**Comment by dims** [comment]
@prometheanfire we need to see if the problem mentioned here is in newer versions:
https://github.com/kubernetes-incubator/client-python/issues/262

**Comment by leeyal** [comment]
Hi , 
I tried to reproduce the issue is #262 without success. 
that the pip freeze output :
`cachetools==2.0.1
certifi==2017.11.5
chardet==3.0.4
google-auth==1.2.1
idna==2.6
ipaddress==1.0.18
kubernetes===4.0.0-snapshot
oauthlib==2.0.6
pyasn1==0.4.2
pyasn1-modules==0.2.1
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
rsa==3.4.2
six==1.11.0
urllib3==1.22
websocket-client==0.44.0
` 

I run the same code as show in #262 and didn't got any certifcate exception ..

**Comment by dims** [comment]
@leeyal  excellent, can you submit a PR that excludes the bad version (0.4.0?) and leaves the cap open?

**Comment by prometheanfire** [comment]
the following versions need to be tested as well to see if it's still broken (these are the versions above 0.40.0 that are published to pypi and are not 0.44.0 (confirmed good). 0.42.0 0.42.1 0.43.0

**Comment by leeyal** [comment]
well i tested it with all version from 0.40.0 between 0.44.0 and it not reproduced , 
two option : 
1. I don't reproduced it in the current way.  
2. the issue is in 0.43.0 that not appears in pip `# pip install websocket-client==0.45.0
Collecting websocket-client==0.45.0
  Could not find a version that satisfies the requirement websocket-client==0.45.0 (from versions: 0.3, 0.4, 0.4.1, 0.5.0a0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.15.0, 0.16.0a0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.39.0, **0.40.0, 0.42.0, 0.42.1, 0.43.0, 0.44.0)**`
